### ISSUE TITLE
[BUG] Hot tubs ain't hot 

### ISSUE THREAD

**Issue by apopanda** [Grantapher/ValheimPlus#27] opened 2023-09-23 00:12 UTC
- **OS:** Linux server hosted on AWS using https://github.com/rileydakota/valheim-ecs-fargate-cdk 
- **Valheim Game Version:** 0.217.14
- **V+ Mod Version:** 0.9.9.17

**Describe the bug**

We have the settings set for autofilling of bonfires and torches. I have a hottub which I kept running since we installed the mod mid-game. Recently, it ran out of wood (hottubs, ovens, smelters and blast furnaces still need fuel). I put wood into it and it isn't lighting up. It keeps having 10 wood and saying it's full, yet no bubbles so no +2 comfort. I destroyed the hottub and rebuilt it, same thing. 

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Set the settings for autofill of torches, bonfires, hearths and such
2. Build a hottub
3. Fill it up
4. No bubbles

**Expected behavior**

Hottub should be working and be providing comfort

**Troubleshooting**

Replaced the hottub, reconnected a bunch of times

**Additional context**

No other mods present

**Comment by VulcanTourist** [comment] 2023-10-02 06:02
This appears to be a duplicate report of Grantapher's own report of the issue, which he says is already tentatively fixed but not yet in a public release:

https://github.com/Grantapher/ValheimPlus/issues/9

**Comment by Grantapher** [comment] 2023-10-04 23:20
Closing as it is in fact a duplicate of #9

**Closed by Grantapher** 2023-10-04 23:20 UTC
Labels: bug
