### ISSUE TITLE
[BUG] Crashes with halloween update

### ISSUE THREAD

**Issue by MBrinks2239** [Grantapher/ValheimPlus#36] opened 2023-11-07 14:04 UTC
- **OS:** Windows Client
- **Valheim Game Version:** 0.217.28
- **V+ Mod Version:** 0.9.10 (Vortex version)

**Describe the bug**

Game crashes on start

**To Reproduce**

1. Start the game
2. Watch it crash.

**Expected behavior**

The game starts.

**Troubleshooting**

Disabling all other mods and reinstalling valheim plus

**Comment by DSDV** [comment] 2023-11-07 14:39
Can confirm on linux native client :( 
Instand crash on pressing the pay button in steam :/

**Comment by stolenvw** [comment] 2023-11-07 14:53
denikson-BepInExPack_Valheim-5.4.2202 should also fix this, it has the unstripped_corlib dir removed and the change in doorstop_config.ini

**Comment by mswietlicki** [comment] 2023-11-08 12:21
@Grantapher I found https://github.com/Grantapher/ValheimPlus/blob/9e3ddcf173878f11016a03b2eddb3e046d11c3e0/bin/create_releases.sh#L3 that is not on any branch, Is this by design? Did you think about creating Github Action with a build. I could help with that,

**Comment by MBrinks2239** [comment] 2023-11-08 12:27
> denikson-BepInExPack_Valheim-5.4.2202 should also fix this, it has the unstripped_corlib dir removed and the change in doorstop_config.ini

I can confirm that this works! Thanks!

@Grantapher want me to close it since that fixes it or do you want me to leave it open so you can improve the incompatibility?

**Comment by werdna87** [comment] 2023-11-10 01:39
I was able to get this working on Windows by copying the files as suggested, but can't seem to get the server to start correctly on linux.

For those of you stumbling along like I did:

The mentioned version of BepInEx can be found here: https://thunderstore.io/package/download/denikson/BepInExPack_Valheim/5.4.2202/

And does work correctly (on windows) if you copy all the files from "BepInExPack_Valheim" on top of V+ installed.

If anyone has suggestions on getting it running on linux, it seems like some of the paths/files changed for mono which seems to be causing issues

**Comment by Grantapher** [comment] 2023-11-11 22:30
Released into [`0.9.11.0`](https://github.com/Grantapher/ValheimPlus/releases/tag/0.9.11.0).

If linux is still an issue, feel free to open another issue for that specifically.

**Closed by Grantapher** 2023-11-11 22:30 UTC
Labels: bug
